import { Opportunity, Scoring, GateRecord, Stage, DetailedScoring, BusinessCase } from "./types";

function scoring(ma: number, sf: number, fe: number, cv: number, ri: number, comments: Record<string, string>): Scoring {
  return {
    marketAttractiveness: { id: "marketAttractiveness", score: ma, comment: comments.marketAttractiveness ?? "" },
    strategicFit: { id: "strategicFit", score: sf, comment: comments.strategicFit ?? "" },
    feasibility: { id: "feasibility", score: fe, comment: comments.feasibility ?? "" },
    commercialViability: { id: "commercialViability", score: cv, comment: comments.commercialViability ?? "" },
    risk: { id: "risk", score: ri, comment: comments.risk ?? "" },
  };
}

export const MOCK_OPPORTUNITIES: Opportunity[] = [
  {
    id: "opp-001",
    title: "Autonomous Navigation Module for Container Ships",
    description: "Development of an AI-driven navigation assistance module targeting mid-size container vessels. Leverages existing sensor technology and partners with classification societies for certification.",
    industry: "Maritime",
    geography: "Europe",
    technology: "AI / Sensor Fusion",
    owner: "Thomas Berger",
    stage: "business_case",
    scoring: scoring(5, 4, 3, 4, 2, {
      marketAttractiveness: "Strong demand from major shipping lines for fuel-efficient autonomous solutions. IMO regulations accelerating adoption.",
      strategicFit: "Aligns with our maritime digitalization roadmap and existing sensor portfolio.",
      feasibility: "Requires sensor fusion expertise; prototype feasible within 12 months. Key partnerships in place.",
      commercialViability: "SaaS + hardware model with €500K per vessel. 60% gross margin at scale.",
      risk: "Regulatory approval timelines uncertain in some flag states. Manageable with classification society partnerships.",
    }),
    detailedScoring: {
      marketAttractiveness: {
        score: 5,
        analysis: {
          tam: "€15B global autonomous shipping market by 2030 (Allied Market Research)",
          tamDescription: "Includes all autonomous navigation, collision avoidance, and remote control systems for commercial vessels globally. Covers full autonomy levels (IMO degrees 1-4) across all vessel types.",
          tamProjections: [{ year: 1, value: 4200 }, { year: 2, value: 6000 }, { year: 3, value: 8500 }, { year: 4, value: 11500 }, { year: 5, value: 15000 }],
          sam: "€3B European container fleet segment — focus on mid-size operators with 50-500 TEU vessels",
          samDescription: "European container operators with fleets >20 vessels that have the infrastructure for retrofit installations. Excludes bulk carriers, tankers, and ultra-large container vessels (>10,000 TEU) due to different regulatory requirements.",
          samProjections: [{ year: 1, value: 900 }, { year: 2, value: 1300 }, { year: 3, value: 1800 }, { year: 4, value: 2300 }, { year: 5, value: 3000 }],
          marketGrowthRate: "18% CAGR through 2030 — driven by IMO regulations, fuel efficiency mandates, and crew shortage",
          targetCustomers: "Mid-size container operators (50-200 vessels): Hapag-Lloyd, CMA CGM feeder fleets, regional operators in Scandinavia and Mediterranean",
          customerRelationship: "Existing partnerships with 3 major operators through sensor sales. LOIs from Hapag-Lloyd and a Norwegian coastal operator.",
          customerSegments: [
            { name: "Large Container Lines", size: 35, description: "Global operators with >500 vessels. High volume, long sales cycles." },
            { name: "Regional Operators", size: 40, description: "Mid-size European operators with 20-200 vessels. Primary target segment." },
            { name: "Coastal/Feeder Services", size: 15, description: "Short-sea shipping operators. High automation potential." },
            { name: "Government/Navy", size: 10, description: "Coast guard and naval auxiliary vessels. Different procurement process." },
          ],
          competitors: "Wärtsilä Voyage (SmartMove), Kongsberg Maritime (K-Bridge ECDIS), Rolls-Royce Marine (Intelligence Awareness System)",
          competitivePosition: "Differentiated by AI-first approach and 40% lower retrofit cost. Faster installation (5 days vs. 3 weeks for competitors). Unique edge: real-time weather routing integration.",
          competitorEntries: [
            { name: "Wärtsilä Voyage", marketShare: 30, threatLevel: 4 },
            { name: "Kongsberg Maritime", marketShare: 25, threatLevel: 4 },
            { name: "Rolls-Royce Marine", marketShare: 15, threatLevel: 3 },
            { name: "Our Company", marketShare: 5, threatLevel: 0 },
            { name: "Others", marketShare: 25, threatLevel: 2 },
          ],
          geographicalRegions: [
            { region: "Scandinavia", potential: 5, marketSize: "€800M", notes: "Most progressive regulation. Norway leading autonomous vessel initiatives." },
            { region: "Mediterranean", potential: 4, marketSize: "€600M", notes: "Large feeder network. Italy and Greece key markets." },
            { region: "North Sea / DACH", potential: 4, marketSize: "€700M", notes: "Dense traffic. Hamburg, Rotterdam, Antwerp corridor." },
            { region: "Asia Pacific", potential: 3, marketSize: "€900M", notes: "Future growth market. Singapore early adopter." },
          ],
        },
      },
      strategicFit: { score: 4, details: "Core maritime digitalization strategy. Leverages existing sensor portfolio and marine engineering team. Extends our digital twin platform into autonomous operations. Minor gap: need to hire 2 ML engineers.",
        alignmentDimensions: [
          { key: "coreCompetency", label: "sfDimCore", current: 4, required: 5 },
          { key: "strategyAlign", label: "sfDimStrategy", current: 5, required: 5 },
          { key: "portfolioSynergy", label: "sfDimPortfolio", current: 4, required: 4 },
          { key: "customerBase", label: "sfDimCustomer", current: 4, required: 4 },
          { key: "technologyFit", label: "sfDimTech", current: 3, required: 5 },
          { key: "channelFit", label: "sfDimChannel", current: 4, required: 4 },
        ],
        capabilityGaps: [
          { id: "cg-001-1", capability: "ML/AI Engineering", currentLevel: 2, requiredLevel: 5, action: "Hire 2 senior ML engineers with maritime domain experience. Partner with TU Hamburg for research collaboration.", priority: "high" },
          { id: "cg-001-2", capability: "Autonomous Systems Certification", currentLevel: 3, requiredLevel: 4, action: "DNV partnership initiated. Internal certification team being trained.", priority: "medium" },
        ],
      },
      feasibility: { score: 3, details: "Sensor fusion expertise in-house. Classification society (DNV) approval process initiated — 8 month timeline. Prototype hardware available. Software stack requires 6 months additional development.", trl: 5, milestones: [
        { id: "ms-001-1", name: "Sensor fusion prototype", targetDate: "2025-12-01", status: "completed" },
        { id: "ms-001-2", name: "DNV certification submission", targetDate: "2026-03-15", status: "in_progress" },
        { id: "ms-001-3", name: "Sea trial alpha", targetDate: "2026-06-01", status: "planned" },
        { id: "ms-001-4", name: "Software stack v1.0", targetDate: "2026-08-15", status: "planned" },
        { id: "ms-001-5", name: "DNV type approval", targetDate: "2026-10-01", status: "planned" },
      ] },
      commercialViability: {
        score: 4,
        details: "SaaS + hardware model. €500K per vessel installation + €50K/year software license. 60% gross margin at 20+ installations. Break-even at 15 vessels.",
        pricingModel: "SaaS + Hardware",
        unitPrice: 500000,
        grossMargin: 60,
        projections: [
          { year: 1, revenue: 12000000, costs: 7000000 },
          { year: 2, revenue: 30000000, costs: 14000000 },
          { year: 3, revenue: 52000000, costs: 22000000 },
          { year: 4, revenue: 75000000, costs: 30000000 },
          { year: 5, revenue: 100000000, costs: 38000000 },
        ],
        breakEvenUnits: 15,
      },
      risk: { score: 2, details: "Regulatory risk manageable — DNV partnership de-risks certification. Technical risk moderate — sensor fusion proven in defense applications.", riskItems: [
        { id: "ri-001-1", name: "DNV certification delay", category: "regulatory", probability: 3, impact: 4, mitigation: "Engage DNV early, parallel submission tracks for different flag states." },
        { id: "ri-001-2", name: "Sensor fusion accuracy", category: "technical", probability: 2, impact: 3, mitigation: "Proven in defense; iterative testing with real vessel data." },
        { id: "ri-001-3", name: "Flag state divergence", category: "regulatory", probability: 4, impact: 3, mitigation: "Focus on early-adopter flag states (Norway, Singapore) first." },
        { id: "ri-001-4", name: "Competitor price war", category: "market", probability: 2, impact: 4, mitigation: "Differentiate on AI-first approach and lower retrofit cost." },
        { id: "ri-001-5", name: "Integration complexity", category: "execution", probability: 3, impact: 2, mitigation: "Modular architecture; pre-integration testing protocol." },
      ] },
    },
    businessCase: {
      investmentCost: 5000000,
      expectedRevenue: 12000000,
      roi: 140,
      breakEvenMonths: 24,
      paybackPeriod: 18,
      npv: 8500000,
      notes: "Based on 24 vessel installations in Year 1, scaling to 60 in Year 2. Conservative TAM penetration of 2%.",
    },
    gates: [
      { id: "g-001a", gate: "gate1", decision: "go", comment: "Strong market pull confirmed through customer interviews. Team unanimously supports proceeding.", decider: "Dr. Claudia Weiss", date: "2025-11-15T10:00:00Z" },
      { id: "g-001b", gate: "gate2", decision: "go", comment: "Detailed market analysis validates €3B SAM. Competitive differentiation clear. DNV partnership secured.", decider: "Michael Braun", date: "2026-01-10T14:00:00Z" },
    ],
    roughScoringAnswers: {
      ma_market_size: 5, ma_growth_rate: 4, ma_customer_demand: 5, ma_competition: 4, ma_accessibility: 4,
      sf_strategy_alignment: 4, sf_competency_match: 4, sf_portfolio_synergy: 4, sf_customer_channel: 4,
      fe_technical_readiness: 3, fe_resources: 3, fe_timeline: 3, fe_dependencies: 4,
      cv_revenue_model: 4, cv_margins: 4, cv_scalability: 4, cv_payback: 4,
      ri_market_risk: 2, ri_technical_risk: 2, ri_execution_risk: 2, ri_financial_risk: 3,
    },
    createdAt: "2025-09-20T08:30:00Z",
  },
  {
    id: "opp-002",
    title: "Hydrogen Fuel Cell Integration for Regional Rail",
    description: "Retrofit solution for diesel regional trains with hydrogen fuel cell powertrains. Targeting European operators with aging fleets under decarbonization mandates.",
    industry: "Rail",
    geography: "DACH / France",
    technology: "Hydrogen Fuel Cells",
    owner: "Markus Schneider",
    stage: "gate1",
    scoring: scoring(4, 5, 3, 3, 3, {
      marketAttractiveness: "EU Green Deal driving strong demand; multiple tenders expected 2026. German and French operators actively seeking solutions.",
      strategicFit: "Core competency in powertrain engineering; direct fit with our rail division's capabilities.",
      feasibility: "Fuel cell integration proven in bus applications. Rail certification (ERA) adds 12-18 months.",
      commercialViability: "High upfront cost (€2.5M per trainset); subsidies required for first deployments. TCO competitive over 20-year lifecycle.",
      risk: "Hydrogen supply chain maturity varies by region. Green hydrogen availability uncertain before 2028 in some markets.",
    }),
    roughScoringAnswers: {
      ma_market_size: 4, ma_growth_rate: 4, ma_customer_demand: 5, ma_competition: 3, ma_accessibility: 3,
      sf_strategy_alignment: 5, sf_competency_match: 5, sf_portfolio_synergy: 4, sf_customer_channel: 4,
      fe_technical_readiness: 3, fe_resources: 3, fe_timeline: 2, fe_dependencies: 3,
      cv_revenue_model: 3, cv_margins: 3, cv_scalability: 3, cv_payback: 2,
      ri_market_risk: 3, ri_technical_risk: 3, ri_execution_risk: 3, ri_financial_risk: 4,
    },
    detailedScoring: {
      marketAttractiveness: {
        score: 4,
        analysis: {
          tam: "€28B global hydrogen rail market by 2035 (Roland Berger)",
          tamDescription: "All hydrogen-powered rail vehicles globally, including new-build and retrofit solutions for regional, commuter, and shunting operations across all track gauges.",
          tamProjections: [{ year: 1, value: 5500 }, { year: 2, value: 6700 }, { year: 3, value: 8200 }, { year: 4, value: 10000 }, { year: 5, value: 12200 }],
          sam: "€4.5B DACH + France retrofit market by 2035 — diesel regional fleets with 15+ years remaining lifecycle",
          samDescription: "Diesel regional rail fleets in Germany, Austria, Switzerland, and France eligible for hydrogen retrofit. Focus on operators with aging Alstom Coradia Lint and Siemens Desiro fleets under decarbonization mandates.",
          samProjections: [{ year: 1, value: 800 }, { year: 2, value: 980 }, { year: 3, value: 1200 }, { year: 4, value: 1460 }, { year: 5, value: 1780 }],
          marketGrowthRate: "22% CAGR through 2035 — EU Green Deal mandates, national hydrogen strategies, and diesel phase-out deadlines",
          targetCustomers: "DB Regio, SNCF TER, ÖBB Regional, BLS (Switzerland). Focus on operators with >50 diesel trainsets facing 2035 diesel bans.",
          customerRelationship: "Long-term framework agreements (10-15 years) with maintenance contracts. Requires OEM partnerships for type approval.",
          customerSegments: [
            { name: "Large national operators", size: 55, description: "DB Regio, SNCF TER — high volume, long procurement cycles" },
            { name: "Regional private operators", size: 30, description: "Transdev, Keolis subsidiaries — faster decision-making, smaller fleets" },
            { name: "State-owned regional railways", size: 15, description: "BLS, Arriva — often mandated by regional governments" },
          ],
          competitors: "Alstom (iLint), Siemens (Mireo Plus H), Stadler — all offering new-build hydrogen trains",
          competitivePosition: "Retrofit niche is underserved. New-build OEMs focus on greenfield; our retrofit approach is 40% cheaper and 18 months faster to deploy.",
          competitorEntries: [
            { name: "Alstom iLint", marketShare: 45, threatLevel: 4 },
            { name: "Siemens Mireo Plus H", marketShare: 25, threatLevel: 4 },
            { name: "Stadler FLIRT H2", marketShare: 15, threatLevel: 3 },
          ],
          geographicalRegions: [
            { region: "Germany", potential: 5, marketSize: "€1.8B", notes: "Largest diesel fleet in Europe. NIP funding available." },
            { region: "France", potential: 4, marketSize: "€1.2B", notes: "SNCF committed to hydrogen for non-electrified lines." },
            { region: "Austria/Switzerland", potential: 3, marketSize: "€500M", notes: "Smaller fleets but strong government support." },
          ],
        },
      },
      strategicFit: { score: 5, details: "Core powertrain engineering competency. Direct extension of our rail division capabilities.", alignmentDimensions: [], capabilityGaps: [] },
      feasibility: { score: 3, details: "Fuel cell integration proven in bus applications. ERA rail certification adds 12-18 months.", trl: 5, milestones: [] },
      commercialViability: {
        score: 3, details: "High upfront cost offset by lifecycle TCO advantage and EU subsidies.",
        pricingModel: "Per-trainset retrofit + maintenance contract",
        unitPrice: 2500000, grossMargin: 28,
        projections: [
          { year: 1, revenue: 5000000, costs: 4200000 },
          { year: 2, revenue: 12500000, costs: 9500000 },
          { year: 3, revenue: 25000000, costs: 17500000 },
          { year: 4, revenue: 40000000, costs: 26000000 },
          { year: 5, revenue: 62000000, costs: 38000000 },
        ],
        breakEvenUnits: 8,
      },
      risk: { score: 3, details: "Hydrogen supply chain maturity varies. Green hydrogen availability uncertain before 2028.", riskItems: [] },
    },
    gates: [],
    createdAt: "2025-10-05T14:20:00Z",
  },
  {
    id: "opp-003",
    title: "Predictive Maintenance Platform for Wind Turbines",
    description: "Cloud-based vibration analytics platform for offshore wind turbine gearboxes. Uses edge sensors and ML models to predict failures 6 weeks in advance.",
    industry: "Energy",
    geography: "Nordics / UK",
    technology: "IoT / Machine Learning",
    owner: "Lisa Hoffmann",
    stage: "rough_scoring",
    scoring: scoring(4, 3, 4, 4, 2, {
      marketAttractiveness: "Offshore wind capacity growing 15% YoY in Europe. O&M costs represent 25% of LCOE.",
      strategicFit: "Extends our industrial IoT portfolio into renewables. Moderate synergy with existing vibration analysis team.",
      feasibility: "Existing sensor hardware can be reused from industrial motors division. ML models in prototype stage — accuracy at 87%.",
      commercialViability: "SaaS model: €15K/turbine/year. Target 500 turbines in Year 1. Gross margin 75%.",
      risk: "Low technical risk. Market entry requires partnerships with turbine OEMs (Vestas, Siemens Gamesa).",
    }),
    roughScoringAnswers: {
      ma_market_size: 4, ma_growth_rate: 5, ma_customer_demand: 4, ma_competition: 3, ma_accessibility: 4,
      sf_strategy_alignment: 3, sf_competency_match: 3, sf_portfolio_synergy: 3, sf_customer_channel: 2,
      fe_technical_readiness: 4, fe_resources: 4, fe_timeline: 4, fe_dependencies: 3,
      cv_revenue_model: 4, cv_margins: 5, cv_scalability: 4, cv_payback: 3,
      ri_market_risk: 2, ri_technical_risk: 2, ri_execution_risk: 2, ri_financial_risk: 1,
    },
    gates: [],
    createdAt: "2025-12-01T09:00:00Z",
  },
  {
    id: "opp-004",
    title: "Defense-Grade Underwater Communication System",
    description: "Acoustic modem for NATO-standard submarine communication. Ultra-low latency, encrypted data links for unmanned underwater vehicles (UUVs).",
    industry: "Defense",
    geography: "NATO countries",
    technology: "Acoustic Communications",
    owner: "Stefan Koch",
    stage: "idea",
    scoring: scoring(3, 4, 2, 3, 4, {
      marketAttractiveness: "NATO underwater modernization programs worth €8B through 2032. Niche market with high barriers to entry.",
      strategicFit: "Extends our underwater sensor portfolio. Leverages sonar expertise from naval division.",
      feasibility: "Requires new acoustic transducer development. ITAR/export control compliance adds complexity. 24-month development estimate.",
      commercialViability: "High unit price (€200K+) but low volume (50-100 units/year). Long procurement cycles offset by multi-year contracts.",
      risk: "Long procurement cycles (3-5 years). Export control restrictions limit addressable markets. TRL currently at 3.",
    }),
    gates: [],
    createdAt: "2026-01-10T11:00:00Z",
  },
  {
    id: "opp-005",
    title: "Aviation Ground Support Robotics",
    description: "Autonomous baggage handling and pushback robots for airport ramp operations. Reduces turnaround time by 20% and eliminates common ground damage incidents.",
    industry: "Aviation",
    geography: "Global (DACH first)",
    technology: "Robotics / Autonomous Systems",
    owner: "Anna Müller",
    stage: "go_to_market",
    scoring: scoring(5, 4, 4, 5, 1, {
      marketAttractiveness: "Airport operators facing chronic labor shortages globally. Ground handling market €45B.",
      strategicFit: "Combines our robotics and automation capabilities with aviation domain knowledge.",
      feasibility: "Proven components from warehouse robotics. Aviation-grade safety certification (DO-178C) achieved.",
      commercialViability: "RaaS model: €8K/robot/month. Payback for airports within 18 months. 65% gross margin.",
      risk: "Low technical risk — proven components. Regulatory environment well understood.",
    }),
    detailedScoring: {
      marketAttractiveness: {
        score: 5,
        analysis: {
          tam: "€45B global ground handling market (IATA 2025). Automation-addressable segment: €12B",
          tamDescription: "All ground handling services worldwide including baggage handling, pushback, de-icing, and cargo loading. Automation-addressable portion limited to repetitive physical tasks on the apron.",
          tamProjections: [{ year: 1, value: 7000 }, { year: 2, value: 10000 }, { year: 3, value: 14000 }, { year: 4, value: 19000 }, { year: 5, value: 25000 }],
          sam: "€2.5B European hub airports (top 50 airports). Initial focus on DACH + Nordics.",
          samDescription: "European airports with >10M PAX/year that have the infrastructure and budget for autonomous ground support. Focus on ramp operations (baggage + pushback) at hub airports.",
          samProjections: [{ year: 1, value: 600 }, { year: 2, value: 900 }, { year: 3, value: 1300 }, { year: 4, value: 1800 }, { year: 5, value: 2500 }],
          marketGrowthRate: "12% CAGR through 2030 — labor shortages and safety regulations driving automation",
          targetCustomers: "Fraport, Swissport, SATS, dnata — hub airport operators with >30M PAX/year.",
          customerRelationship: "Fraport: pilot partner since 2025, LOI for 40 robots. Swissport: MOU signed.",
          customerSegments: [
            { name: "Hub Airport Operators", size: 45, description: "Major hub airports managing own ground handling. High volume, early adopters." },
            { name: "Ground Handling Companies", size: 35, description: "Third-party handlers (Swissport, dnata). Scale-driven, cost-sensitive." },
            { name: "Regional Airports", size: 15, description: "Smaller airports exploring automation. Lower volume, longer sales cycles." },
            { name: "Military/Government", size: 5, description: "Military airfields with specialized requirements." },
          ],
          competitors: "ThorDrive (US, early stage), Gaussian Robotics (China, outdoor cleaning), KUKA (industrial, not aviation-specific)",
          competitivePosition: "Only solution with DO-178C aviation safety certification. 3x faster deployment. Patent on obstacle avoidance.",
          competitorEntries: [
            { name: "ThorDrive", marketShare: 5, threatLevel: 3 },
            { name: "Gaussian Robotics", marketShare: 10, threatLevel: 2 },
            { name: "KUKA", marketShare: 15, threatLevel: 2 },
            { name: "Our Company", marketShare: 8, threatLevel: 0 },
            { name: "Manual Operations", marketShare: 62, threatLevel: 1 },
          ],
          geographicalRegions: [
            { region: "DACH", potential: 5, marketSize: "€600M", notes: "Fraport pilot success. Strong labor shortage. High automation acceptance." },
            { region: "Nordics", potential: 4, marketSize: "€350M", notes: "Progressive regulations. High labor costs drive ROI." },
            { region: "UK & Ireland", potential: 3, marketSize: "€400M", notes: "Heathrow and Dublin interested. Post-Brexit regulatory complexity." },
            { region: "Middle East", potential: 4, marketSize: "€500M", notes: "Dubai, Doha mega-hubs. High budgets, new infrastructure." },
          ],
        },
      },
      strategicFit: { score: 4, details: "Strong robotics DNA from industrial division. Aviation domain expertise from 10+ years of consulting. Gap: need dedicated aviation sales team (3 FTEs).",
        alignmentDimensions: [
          { key: "coreCompetency", label: "sfDimCore", current: 5, required: 5 },
          { key: "strategyAlign", label: "sfDimStrategy", current: 4, required: 5 },
          { key: "portfolioSynergy", label: "sfDimPortfolio", current: 4, required: 4 },
          { key: "customerBase", label: "sfDimCustomer", current: 3, required: 5 },
          { key: "technologyFit", label: "sfDimTech", current: 5, required: 5 },
          { key: "channelFit", label: "sfDimChannel", current: 2, required: 4 },
        ],
        capabilityGaps: [
          { id: "cg-005-1", capability: "Aviation Sales Team", currentLevel: 1, requiredLevel: 4, action: "Hire 3 FTEs with aviation ground handling experience. Target ex-Swissport/dnata sales managers.", priority: "high" },
          { id: "cg-005-2", capability: "Airport Partner Network", currentLevel: 3, requiredLevel: 5, action: "Expand from Fraport pilot to 5+ airport partnerships. Attend inter airport Europe 2026.", priority: "medium" },
          { id: "cg-005-3", capability: "Aviation Regulatory Expertise", currentLevel: 4, requiredLevel: 4, action: "Existing DO-178C expertise sufficient. Maintain EASA working group participation.", priority: "low" },
        ],
      },
      feasibility: { score: 4, details: "Core navigation from warehouse robotics (TRL 8). Aviation safety certification (DO-178C) completed Q3 2025. Frankfurt pilot: 6 months, zero incidents, 22% turnaround improvement.", trl: 8, milestones: [
        { id: "ms-005-1", name: "Warehouse robotics adaptation", targetDate: "2025-03-01", status: "completed" },
        { id: "ms-005-2", name: "DO-178C certification", targetDate: "2025-09-30", status: "completed" },
        { id: "ms-005-3", name: "Frankfurt airport pilot", targetDate: "2025-12-01", status: "completed" },
        { id: "ms-005-4", name: "Production ramp-up", targetDate: "2026-02-01", status: "in_progress" },
      ] },
      commercialViability: {
        score: 5,
        details: "RaaS model: €8K/robot/month (36-month contracts). COGS: €35K/robot. At 200 robots deployed: €19.2M ARR, 65% gross margin.",
        pricingModel: "RaaS (Robot-as-a-Service)",
        unitPrice: 96000,
        grossMargin: 65,
        projections: [
          { year: 1, revenue: 7680000, costs: 5500000 },
          { year: 2, revenue: 19200000, costs: 8000000 },
          { year: 3, revenue: 38400000, costs: 14000000 },
          { year: 4, revenue: 57600000, costs: 20000000 },
          { year: 5, revenue: 76800000, costs: 26000000 },
        ],
        breakEvenUnits: 50,
      },
      risk: { score: 1, details: "Technical: proven in pilot (TRL 8). Regulatory: DO-178C certified. Market: strong demand validated.", riskItems: [
        { id: "ri-005-1", name: "Airport regulatory changes", category: "regulatory", probability: 1, impact: 3, mitigation: "DO-178C certification already achieved. Active participation in EASA working groups." },
        { id: "ri-005-2", name: "Robot malfunction on ramp", category: "technical", probability: 1, impact: 5, mitigation: "Triple-redundant safety systems. 6-month pilot with zero incidents." },
        { id: "ri-005-3", name: "Scaling production", category: "execution", probability: 2, impact: 3, mitigation: "Contract manufacturing partnership with Foxconn. Buffer stock strategy." },
      ] },
    },
    businessCase: {
      investmentCost: 8000000,
      expectedRevenue: 19200000,
      roi: 180,
      breakEvenMonths: 16,
      paybackPeriod: 14,
      npv: 15000000,
      notes: "Year 1: 80 robots at Fraport + Swissport. Year 2: scale to 200 robots across 8 airports. Revenue: 100% RaaS recurring.",
    },
    gates: [
      { id: "g-005a", gate: "gate1", decision: "go", comment: "Excellent market fit confirmed. Labor shortage is an acute pain point. Unanimous go.", decider: "Dr. Claudia Weiss", date: "2025-07-20T09:00:00Z" },
      { id: "g-005b", gate: "gate2", decision: "go", comment: "Outstanding detail scoring. Competitive moat through aviation certification is unique.", decider: "Michael Braun", date: "2025-10-10T14:00:00Z" },
      { id: "g-005c", gate: "gate3", decision: "go", comment: "Business case compelling — 180% ROI. Handing off to product management for launch Q1 2026.", decider: "Dr. Claudia Weiss", date: "2025-12-10T14:00:00Z" },
    ],
    roughScoringAnswers: {
      ma_market_size: 5, ma_growth_rate: 5, ma_customer_demand: 5, ma_competition: 5, ma_accessibility: 4,
      sf_strategy_alignment: 4, sf_competency_match: 5, sf_portfolio_synergy: 4, sf_customer_channel: 3,
      fe_technical_readiness: 5, fe_resources: 4, fe_timeline: 4, fe_dependencies: 3,
      cv_revenue_model: 5, cv_margins: 5, cv_scalability: 5, cv_payback: 5,
      ri_market_risk: 1, ri_technical_risk: 1, ri_execution_risk: 1, ri_financial_risk: 1,
    },
    createdAt: "2025-05-15T07:30:00Z",
  },
  {
    id: "opp-006",
    title: "Rail Track Inspection Drone Service",
    description: "Drone-based visual and thermal inspection service for railway infrastructure. Subscription model targeting European rail operators.",
    industry: "Rail",
    geography: "Europe",
    technology: "Drones / Computer Vision",
    owner: "Thomas Berger",
    stage: "closed",
    scoring: scoring(3, 2, 4, 2, 4, {
      marketAttractiveness: "Niche market (€800M) with strong incumbents like Fugro and Plasser & Theurer.",
      strategicFit: "Limited synergy with core portfolio. Would require building drone operations capability from scratch.",
      feasibility: "Drone technology mature. Integration with rail-specific inspection standards (EN 13848) achievable.",
      commercialViability: "Subscription model viable but margins thin (35%). Price pressure from incumbents.",
      risk: "High competition from established inspection companies. BVLOS drone regulations still evolving.",
    }),
    gates: [
      { id: "g-006", gate: "gate1", decision: "no-go", comment: "Insufficient strategic fit — would require building entirely new capability. Market differentiation unclear.", decider: "Michael Braun", date: "2026-01-25T16:00:00Z" },
    ],
    roughScoringAnswers: {
      ma_market_size: 3, ma_growth_rate: 3, ma_customer_demand: 3, ma_competition: 2, ma_accessibility: 2,
      sf_strategy_alignment: 2, sf_competency_match: 2, sf_portfolio_synergy: 2, sf_customer_channel: 2,
      fe_technical_readiness: 4, fe_resources: 3, fe_timeline: 4, fe_dependencies: 3,
      cv_revenue_model: 2, cv_margins: 2, cv_scalability: 3, cv_payback: 2,
      ri_market_risk: 4, ri_technical_risk: 3, ri_execution_risk: 4, ri_financial_risk: 4,
    },
    createdAt: "2025-11-01T10:00:00Z",
  },
  {
    id: "opp-007",
    title: "Collaborative Welding Robot for Shipyards",
    description: "Lightweight cobot solution for automated welding in confined ship compartments. Reduces manual welding hours by 40%.",
    industry: "Shipbuilding",
    geography: "Europe / South Korea",
    technology: "Cobots / Welding Automation",
    owner: "Lisa Hoffmann",
    stage: "detailed_scoring",
    scoring: scoring(4, 5, 3, 4, 2, {
      marketAttractiveness: "Shipyards worldwide struggling with skilled welder shortage. 30% of welders retiring within 5 years.",
      strategicFit: "Perfect fit with our robotics and maritime divisions. Combines two core competencies.",
      feasibility: "Requires custom end-effector development; 18-month timeline. Cobot platform (UR20) available off-the-shelf.",
      commercialViability: "€150K per cobot system. Target 30 units Year 1. Recurring revenue from consumables (€20K/year).",
      risk: "Moderate technical risk in confined-space navigation. Classification society acceptance of cobot welds needs validation.",
    }),
    detailedScoring: {
      marketAttractiveness: {
        score: 4,
        analysis: {
          tam: "€6B global shipyard automation market (Frost & Sullivan 2025). Welding automation subset: €1.8B",
          tamDescription: "All automation systems used in shipbuilding including cutting, welding, painting, and assembly. Welding automation covers robotic and semi-automated welding across hull construction, outfitting, and pipe work.",
          tamProjections: [{ year: 1, value: 1800 }, { year: 2, value: 2200 }, { year: 3, value: 3000 }, { year: 4, value: 4200 }, { year: 5, value: 6000 }],
          sam: "€450M European and South Korean shipyards. Focus on mid-size yards building offshore vessels and cruise ships.",
          samDescription: "European and Korean shipyards with confined-space welding needs — specifically yards building cruise ships, offshore vessels, and naval ships where compartment welding is >40% of total welding hours.",
          samProjections: [{ year: 1, value: 150 }, { year: 2, value: 200 }, { year: 3, value: 270 }, { year: 4, value: 360 }, { year: 5, value: 450 }],
          marketGrowthRate: "8% CAGR through 2030 — welder shortage and quality requirements driving adoption",
          targetCustomers: "Meyer Werft (Germany), Fincantieri (Italy), HD Hyundai (Korea), Damen Shipyards (Netherlands).",
          customerRelationship: "Meyer Werft: existing customer for industrial robots. Fincantieri: discussions initiated through maritime trade shows.",
          customerSegments: [
            { name: "Cruise Ship Builders", size: 30, description: "Highest compartment welding ratio. Premium quality requirements." },
            { name: "Offshore Vessel Yards", size: 25, description: "Complex structures with many confined spaces. Growing segment." },
            { name: "Naval Shipyards", size: 20, description: "Military vessels with stringent quality standards. Long procurement." },
            { name: "Commercial Ship Yards", size: 25, description: "Container and bulk carrier builders. More open-space welding." },
          ],
          competitors: "Pemamek (Finland, heavy welding automation), Kranendonk (Netherlands, pipe welding), Bug-O Systems (US, track welding).",
          competitivePosition: "Unique: only cobot solution designed for confined compartments (<2m ceiling). Lighter (28kg) than any competitor. Patent pending.",
          competitorEntries: [
            { name: "Pemamek", marketShare: 20, threatLevel: 3 },
            { name: "Kranendonk", marketShare: 15, threatLevel: 3 },
            { name: "Bug-O Systems", marketShare: 10, threatLevel: 2 },
            { name: "Manual Welding", marketShare: 50, threatLevel: 1 },
            { name: "Our Company", marketShare: 5, threatLevel: 0 },
          ],
          geographicalRegions: [
            { region: "Germany", potential: 5, marketSize: "€120M", notes: "Meyer Werft anchor customer. Strong cobot adoption culture." },
            { region: "Italy", potential: 4, marketSize: "€100M", notes: "Fincantieri — world's largest cruise ship builder. Active discussions." },
            { region: "South Korea", potential: 4, marketSize: "€150M", notes: "HD Hyundai, Samsung Heavy. High volume but requires local presence." },
            { region: "Netherlands/Scandinavia", potential: 3, marketSize: "€80M", notes: "Damen, Ulstein. Smaller yards but innovation-friendly." },
          ],
        },
      },
      strategicFit: { score: 5, details: "Combines robotics division expertise with maritime division domain knowledge. CEO priority project — aligns with 'Smart Shipyard' strategic initiative.",
        alignmentDimensions: [
          { key: "coreCompetency", label: "sfDimCore", current: 5, required: 5 },
          { key: "strategyAlign", label: "sfDimStrategy", current: 5, required: 5 },
          { key: "portfolioSynergy", label: "sfDimPortfolio", current: 5, required: 4 },
          { key: "customerBase", label: "sfDimCustomer", current: 4, required: 4 },
          { key: "technologyFit", label: "sfDimTech", current: 4, required: 5 },
          { key: "channelFit", label: "sfDimChannel", current: 3, required: 4 },
        ],
        capabilityGaps: [
          { id: "cg-007-1", capability: "Welding Process Expertise", currentLevel: 3, requiredLevel: 5, action: "Hire welding engineer from shipyard. Partnership with Fronius for welding technology.", priority: "high" },
          { id: "cg-007-2", capability: "Korean Market Access", currentLevel: 1, requiredLevel: 4, action: "Establish HD Hyundai partnership. Hire Korean-speaking BD manager.", priority: "medium" },
        ],
      },
      feasibility: { score: 3, details: "Cobot platform: UR20 off-the-shelf (TRL 9). Custom end-effector: design phase complete, prototype in 4 months. Total timeline: 18 months to market-ready.", trl: 4, milestones: [
        { id: "ms-007-1", name: "End-effector design complete", targetDate: "2026-01-15", status: "completed" },
        { id: "ms-007-2", name: "Prototype build", targetDate: "2026-05-01", status: "in_progress" },
        { id: "ms-007-3", name: "Weld quality testing", targetDate: "2026-08-01", status: "planned" },
        { id: "ms-007-4", name: "Shipyard field trial", targetDate: "2026-11-01", status: "planned" },
        { id: "ms-007-5", name: "Classification approval", targetDate: "2027-03-01", status: "planned" },
      ] },
      commercialViability: {
        score: 4,
        details: "System price: €150K. Gross margin: 55%. Recurring: €20K/year. Customer ROI: replaces 1.5 FTE welders — payback in 18 months.",
        pricingModel: "Hardware + Service",
        unitPrice: 150000,
        grossMargin: 55,
        projections: [
          { year: 1, revenue: 4500000, costs: 3200000 },
          { year: 2, revenue: 10500000, costs: 6000000 },
          { year: 3, revenue: 18000000, costs: 9000000 },
          { year: 4, revenue: 27000000, costs: 12000000 },
          { year: 5, revenue: 36000000, costs: 15000000 },
        ],
        breakEvenUnits: 20,
      },
      risk: { score: 2, details: "Technical: confined-space navigation is novel but simulation results promising (98.5% collision avoidance). Market: welder shortage is structural.", riskItems: [
        { id: "ri-007-1", name: "Confined-space navigation failure", category: "technical", probability: 3, impact: 5, mitigation: "Simulation results at 98.5% collision avoidance. Additional LiDAR backup sensor planned." },
        { id: "ri-007-2", name: "Weld quality rejection", category: "technical", probability: 2, impact: 4, mitigation: "Pre-qualification with DNV and Lloyd's Register. Extensive testing protocol." },
        { id: "ri-007-3", name: "Classification society resistance", category: "regulatory", probability: 3, impact: 4, mitigation: "Early engagement with DNV, BV, and Lloyd's. Joint R&D project proposed." },
        { id: "ri-007-4", name: "Skilled operator shortage", category: "execution", probability: 2, impact: 2, mitigation: "Intuitive UI design. 2-day training program. Remote support capability." },
      ] },
    },
    gates: [
      { id: "g-007", gate: "gate1", decision: "go", comment: "Clear differentiation in a growing niche. Welder shortage is structural. Approved for detailed analysis.", decider: "Dr. Claudia Weiss", date: "2026-01-05T11:30:00Z" },
    ],
    roughScoringAnswers: {
      ma_market_size: 4, ma_growth_rate: 4, ma_customer_demand: 5, ma_competition: 4, ma_accessibility: 3,
      sf_strategy_alignment: 5, sf_competency_match: 5, sf_portfolio_synergy: 5, sf_customer_channel: 4,
      fe_technical_readiness: 3, fe_resources: 3, fe_timeline: 3, fe_dependencies: 3,
      cv_revenue_model: 4, cv_margins: 4, cv_scalability: 3, cv_payback: 4,
      ri_market_risk: 2, ri_technical_risk: 3, ri_execution_risk: 2, ri_financial_risk: 2,
    },
    createdAt: "2025-10-20T13:00:00Z",
  },
  {
    id: "opp-008",
    title: "Smart Grid Battery Management System",
    description: "Software platform for optimizing battery storage dispatch in industrial microgrids. AI-based forecasting for peak shaving and grid services revenue.",
    industry: "Energy",
    geography: "DACH / Benelux",
    technology: "AI / Energy Storage",
    owner: "Markus Schneider",
    stage: "gate1",
    scoring: scoring(4, 3, 4, 5, 2, {
      marketAttractiveness: "Industrial energy storage market CAGR 25% through 2030. EU energy crisis accelerating adoption. €12B market by 2028.",
      strategicFit: "Moderate fit — extends our industrial IoT platform but requires new energy trading domain expertise.",
      feasibility: "Core optimization algorithms exist from process industry projects. Energy market interface (EPEX SPOT) requires new development.",
      commercialViability: "SaaS model: €5K/month per site. Revenue share on grid services (10% of customer earnings). 80% margins at scale.",
      risk: "Low technical risk. Regulatory risk around grid services market rules varies by country.",
    }),
    roughScoringAnswers: {
      ma_market_size: 4, ma_growth_rate: 5, ma_customer_demand: 4, ma_competition: 3, ma_accessibility: 3,
      sf_strategy_alignment: 3, sf_competency_match: 3, sf_portfolio_synergy: 3, sf_customer_channel: 2,
      fe_technical_readiness: 4, fe_resources: 4, fe_timeline: 4, fe_dependencies: 3,
      cv_revenue_model: 5, cv_margins: 5, cv_scalability: 5, cv_payback: 4,
      ri_market_risk: 2, ri_technical_risk: 2, ri_execution_risk: 2, ri_financial_risk: 2,
    },
    detailedScoring: {
      marketAttractiveness: {
        score: 4,
        analysis: {
          tam: "€18B global industrial energy storage software market by 2030 (BloombergNEF)",
          tamDescription: "All software platforms for battery storage optimization in industrial, commercial, and utility-scale applications. Includes dispatch optimization, forecasting, and grid services orchestration.",
          tamProjections: [{ year: 1, value: 4500 }, { year: 2, value: 5600 }, { year: 3, value: 7000 }, { year: 4, value: 8800 }, { year: 5, value: 11000 }],
          sam: "€2.8B DACH + Benelux industrial microgrid segment by 2030 — manufacturers with >1 MW battery installations",
          samDescription: "Industrial sites in DACH and Benelux with existing or planned battery storage >1 MW. Focus on manufacturing, logistics centers, and data centers with high energy costs and grid services potential.",
          samProjections: [{ year: 1, value: 500 }, { year: 2, value: 625 }, { year: 3, value: 780 }, { year: 4, value: 975 }, { year: 5, value: 1220 }],
          marketGrowthRate: "25% CAGR through 2030 — energy crisis, falling battery costs, and grid services revenue driving adoption",
          targetCustomers: "Large industrial energy consumers: BASF, ThyssenKrupp, BMW plants, DHL logistics hubs. Also data center operators (Equinix, NTT).",
          customerRelationship: "SaaS subscriptions with revenue-share on grid services earnings. Long-term contracts (3-5 years) with performance guarantees.",
          customerSegments: [
            { name: "Heavy manufacturing", size: 45, description: "Steel, chemicals, automotive — high energy costs, large battery installations" },
            { name: "Logistics & warehousing", size: 30, description: "Distribution centers with EV charging and solar — growing fast" },
            { name: "Data centers", size: 25, description: "UPS battery repurposing for grid services — high margin opportunity" },
          ],
          competitors: "Fluence (Siemens/AES), Tesla Autobidder, Stem Inc., enspired",
          competitivePosition: "Differentiated through industrial process integration — competitors focus on pure grid trading. Our IoT platform gives us unique load forecasting advantage.",
          competitorEntries: [
            { name: "Fluence", marketShare: 30, threatLevel: 4 },
            { name: "Tesla Autobidder", marketShare: 20, threatLevel: 3 },
            { name: "Stem Inc.", marketShare: 15, threatLevel: 3 },
          ],
          geographicalRegions: [
            { region: "Germany", potential: 5, marketSize: "€1.5B", notes: "Highest industrial energy costs in EU. Strong grid services market." },
            { region: "Netherlands", potential: 4, marketSize: "€600M", notes: "Fast-growing battery market. EPEX SPOT hub." },
            { region: "Belgium/Luxembourg", potential: 3, marketSize: "€350M", notes: "Smaller but well-regulated market with clear grid code." },
            { region: "Austria/Switzerland", potential: 3, marketSize: "€350M", notes: "Growing demand, favorable regulatory environment." },
          ],
        },
      },
      strategicFit: { score: 3, details: "Extends industrial IoT platform. Requires new energy trading domain expertise.", alignmentDimensions: [], capabilityGaps: [] },
      feasibility: { score: 4, details: "Core optimization algorithms exist. EPEX SPOT interface requires 6 months new development.", trl: 6, milestones: [] },
      commercialViability: {
        score: 5, details: "SaaS + revenue share model. 80% margins at scale.",
        pricingModel: "SaaS subscription + 10% revenue share on grid services",
        unitPrice: 60000, grossMargin: 80,
        projections: [
          { year: 1, revenue: 1200000, costs: 800000 },
          { year: 2, revenue: 3600000, costs: 1500000 },
          { year: 3, revenue: 8500000, costs: 2800000 },
          { year: 4, revenue: 16000000, costs: 4500000 },
          { year: 5, revenue: 28000000, costs: 7000000 },
        ],
        breakEvenUnits: 15,
      },
      risk: { score: 2, details: "Low technical risk. Regulatory uncertainty around grid services rules varies by country.", riskItems: [] },
    },
    gates: [],
    createdAt: "2025-12-15T08:00:00Z",
  },
];
