import { Opportunity, Scoring, GateRecord, Stage, DetailedScoring, BusinessCase } from "./types";

function scoring(ma: number, sf: number, fe: number, cv: number, ri: number, comments: Record<string, string>): Scoring {
  return {
    marketAttractiveness: { id: "marketAttractiveness", score: ma, comment: comments.marketAttractiveness ?? "" },
    strategicFit: { id: "strategicFit", score: sf, comment: comments.strategicFit ?? "" },
    feasibility: { id: "feasibility", score: fe, comment: comments.feasibility ?? "" },
    commercialViability: { id: "commercialViability", score: cv, comment: comments.commercialViability ?? "" },
    risk: { id: "risk", score: ri, comment: comments.risk ?? "" },
  };
}

export const MOCK_OPPORTUNITIES: Opportunity[] = [
  {
    id: "opp-001",
    title: "Autonomous Navigation Module for Container Ships",
    description: "Development of an AI-driven navigation assistance module targeting mid-size container vessels. Leverages existing sensor technology and partners with classification societies for certification.",
    market: "Marine",
    owner: "Thomas Berger",
    stage: "business_case",
    scoring: scoring(5, 4, 3, 4, 2, {
      marketAttractiveness: "Strong demand from major shipping lines for fuel-efficient autonomous solutions. IMO regulations accelerating adoption.",
      strategicFit: "Aligns with our maritime digitalization roadmap and existing sensor portfolio.",
      feasibility: "Requires sensor fusion expertise; prototype feasible within 12 months. Key partnerships in place.",
      commercialViability: "SaaS + hardware model with €500K per vessel. 60% gross margin at scale.",
      risk: "Regulatory approval timelines uncertain in some flag states. Manageable with classification society partnerships.",
    }),
    detailedScoring: {
      marketAttractiveness: {
        score: 5,
        analysis: {
          tam: "€15B global autonomous shipping market by 2030 (Allied Market Research)",
          sam: "€3B European container fleet segment — focus on mid-size operators with 50-500 TEU vessels",
          targetCustomers: "Mid-size container operators (50-200 vessels): Hapag-Lloyd, CMA CGM feeder fleets, regional operators in Scandinavia and Mediterranean",
          customerRelationship: "Existing partnerships with 3 major operators through sensor sales. LOIs from Hapag-Lloyd and a Norwegian coastal operator.",
          competitors: "Wärtsilä Voyage (SmartMove), Kongsberg Maritime (K-Bridge ECDIS), Rolls-Royce Marine (Intelligence Awareness System)",
          competitivePosition: "Differentiated by AI-first approach and 40% lower retrofit cost. Faster installation (5 days vs. 3 weeks for competitors). Unique edge: real-time weather routing integration.",
        },
      },
      strategicFit: { score: 4, details: "Core maritime digitalization strategy. Leverages existing sensor portfolio and marine engineering team. Extends our digital twin platform into autonomous operations. Minor gap: need to hire 2 ML engineers." },
      feasibility: { score: 3, details: "Sensor fusion expertise in-house. Classification society (DNV) approval process initiated — 8 month timeline. Prototype hardware available. Software stack requires 6 months additional development. Key risk: integration with legacy bridge systems." },
      commercialViability: { score: 4, details: "SaaS + hardware model. €500K per vessel installation + €50K/year software license. 60% gross margin at 20+ installations. Break-even at 15 vessels. Customer payback through 12% fuel savings." },
      risk: { score: 2, details: "Regulatory risk manageable — DNV partnership de-risks certification. Technical risk moderate — sensor fusion proven in defense applications. Market risk low — IMO mandates drive adoption. Insurance implications being assessed with P&I clubs." },
    },
    businessCase: {
      investmentCost: 5000000,
      expectedRevenue: 12000000,
      roi: 140,
      breakEvenMonths: 24,
      paybackPeriod: 18,
      npv: 8500000,
      notes: "Based on 24 vessel installations in Year 1, scaling to 60 in Year 2. Conservative TAM penetration of 2%. Assumes €2M in development costs (already spent) + €3M for go-to-market and team expansion. Revenue model: 70% hardware, 30% SaaS recurring. Sensitivity: 20% fewer installations still yields positive NPV of €4.2M.",
    },
    gates: [
      { id: "g-001a", gate: "gate1", decision: "go", comment: "Strong market pull confirmed through customer interviews. Team unanimously supports proceeding. Rough scoring shows high market attractiveness and strategic fit.", decider: "Dr. Claudia Weiss", date: "2025-11-15T10:00:00Z" },
      { id: "g-001b", gate: "gate2", decision: "go", comment: "Detailed market analysis validates €3B SAM. Competitive differentiation clear. DNV partnership secured. Approved for full business case development.", decider: "Michael Braun", date: "2026-01-10T14:00:00Z" },
    ],
    createdAt: "2025-09-20T08:30:00Z",
  },
  {
    id: "opp-002",
    title: "Hydrogen Fuel Cell Integration for Regional Rail",
    description: "Retrofit solution for diesel regional trains with hydrogen fuel cell powertrains. Targeting European operators with aging fleets under decarbonization mandates.",
    market: "Hydrogen",
    owner: "Markus Schneider",
    stage: "gate1",
    scoring: scoring(4, 5, 3, 3, 3, {
      marketAttractiveness: "EU Green Deal driving strong demand; multiple tenders expected 2026. German and French operators actively seeking solutions.",
      strategicFit: "Core competency in powertrain engineering; direct fit with our rail division's capabilities.",
      feasibility: "Fuel cell integration proven in bus applications. Rail certification (ERA) adds 12-18 months. Supply chain for MEA stacks needs securing.",
      commercialViability: "High upfront cost (€2.5M per trainset); subsidies required for first deployments. TCO competitive over 20-year lifecycle.",
      risk: "Hydrogen supply chain maturity varies by region. Green hydrogen availability uncertain before 2028 in some markets.",
    }),
    gates: [],
    createdAt: "2025-10-05T14:20:00Z",
  },
  {
    id: "opp-003",
    title: "Predictive Maintenance Platform for Wind Turbines",
    description: "Cloud-based vibration analytics platform for offshore wind turbine gearboxes. Uses edge sensors and ML models to predict failures 6 weeks in advance.",
    market: "Energy",
    owner: "Lisa Hoffmann",
    stage: "rough_scoring",
    scoring: scoring(4, 3, 4, 4, 2, {
      marketAttractiveness: "Offshore wind capacity growing 15% YoY in Europe. O&M costs represent 25% of LCOE — predictive maintenance can reduce this by 30%.",
      strategicFit: "Extends our industrial IoT portfolio into renewables. Moderate synergy with existing vibration analysis team.",
      feasibility: "Existing sensor hardware can be reused from industrial motors division. ML models in prototype stage — accuracy at 87% on test data.",
      commercialViability: "SaaS model: €15K/turbine/year. Target 500 turbines in Year 1. Gross margin 75% after platform development.",
      risk: "Low technical risk. Market entry requires partnerships with turbine OEMs (Vestas, Siemens Gamesa). Data access agreements needed.",
    }),
    gates: [],
    createdAt: "2025-12-01T09:00:00Z",
  },
  {
    id: "opp-004",
    title: "Defense-Grade Underwater Communication System",
    description: "Acoustic modem for NATO-standard submarine communication. Ultra-low latency, encrypted data links for unmanned underwater vehicles (UUVs).",
    market: "Defense",
    owner: "Stefan Koch",
    stage: "idea",
    scoring: scoring(3, 4, 2, 3, 4, {
      marketAttractiveness: "NATO underwater modernization programs worth €8B through 2032. Niche market with high barriers to entry.",
      strategicFit: "Extends our underwater sensor portfolio. Leverages sonar expertise from naval division.",
      feasibility: "Requires new acoustic transducer development. ITAR/export control compliance adds complexity. 24-month development estimate.",
      commercialViability: "High unit price (€200K+) but low volume (50-100 units/year). Long procurement cycles offset by multi-year framework contracts.",
      risk: "Long procurement cycles (3-5 years). Export control restrictions limit addressable markets. Technology readiness level currently at TRL 3.",
    }),
    gates: [],
    createdAt: "2026-01-10T11:00:00Z",
  },
  {
    id: "opp-005",
    title: "Aviation Ground Support Robotics",
    description: "Autonomous baggage handling and pushback robots for airport ramp operations. Reduces turnaround time by 20% and eliminates common ground damage incidents.",
    market: "Aviation",
    owner: "Anna Müller",
    stage: "go_to_market",
    scoring: scoring(5, 4, 4, 5, 1, {
      marketAttractiveness: "Airport operators facing chronic labor shortages globally. Ground handling market €45B. Automation penetration below 5%.",
      strategicFit: "Combines our robotics and automation capabilities with aviation domain knowledge from consulting division.",
      feasibility: "Proven components from warehouse robotics. Aviation-grade safety certification (DO-178C) achieved. Frankfurt Airport pilot successful.",
      commercialViability: "RaaS model: €8K/robot/month. Payback for airports within 18 months vs. manual labor. 65% gross margin.",
      risk: "Low technical risk — proven components. Regulatory environment well understood. Airport unions may resist adoption in some markets.",
    }),
    detailedScoring: {
      marketAttractiveness: {
        score: 5,
        analysis: {
          tam: "€45B global ground handling market (IATA 2025). Automation-addressable segment: €12B",
          sam: "€2.5B European hub airports (top 50 airports). Initial focus on DACH + Nordics.",
          targetCustomers: "Fraport, Swissport, SATS, dnata — hub airport operators with >30M PAX/year. Also targeting ground handling service companies.",
          customerRelationship: "Fraport: pilot partner since 2025, LOI for 40 robots. Swissport: MOU signed. SATS Singapore: initial discussions.",
          competitors: "ThorDrive (US, early stage), Gaussian Robotics (China, outdoor cleaning), KUKA (industrial, not aviation-specific)",
          competitivePosition: "Only solution with DO-178C aviation safety certification. 3x faster deployment vs. custom solutions. Patent on obstacle avoidance in congested ramp environments.",
        },
      },
      strategicFit: { score: 4, details: "Strong robotics DNA from industrial division. Aviation domain expertise from 10+ years of consulting. Gap: need dedicated aviation sales team (3 FTEs). Technology synergies with warehouse automation division — shared navigation stack." },
      feasibility: { score: 4, details: "Core navigation and manipulation from warehouse robotics (TRL 8). Aviation safety certification (DO-178C) completed Q3 2025. Frankfurt pilot: 6 months, zero incidents, 22% turnaround improvement. Manufacturing partner secured (Foxconn contract)." },
      commercialViability: { score: 5, details: "RaaS model: €8K/robot/month (36-month contracts). COGS: €35K/robot. Payback for customer: 18 months vs. manual labor (€14/hour, 3 shifts). At 200 robots deployed: €19.2M ARR, 65% gross margin. Upsell: data analytics add-on €2K/month." },
      risk: { score: 1, details: "Technical: proven in pilot (TRL 8). Regulatory: DO-178C certified. Market: strong demand validated. Labor relations: working with airport unions on transition plans. Insurance: Allianz Aviation partnership for liability coverage." },
    },
    businessCase: {
      investmentCost: 8000000,
      expectedRevenue: 19200000,
      roi: 180,
      breakEvenMonths: 16,
      paybackPeriod: 14,
      npv: 15000000,
      notes: "Year 1: 80 robots at Fraport + Swissport. Year 2: scale to 200 robots across 8 airports. Development costs €5M (completed), go-to-market €3M. Revenue: 100% RaaS recurring. Churn assumption: <5% annually. Upside: data analytics add-on not included in base case (potential +€4.8M ARR at scale).",
    },
    gates: [
      { id: "g-005a", gate: "gate1", decision: "go", comment: "Excellent market fit confirmed. Labor shortage is an acute pain point. Team sees clear path to prototype. Unanimous go.", decider: "Dr. Claudia Weiss", date: "2025-07-20T09:00:00Z" },
      { id: "g-005b", gate: "gate2", decision: "go", comment: "Outstanding detail scoring. TAM/SAM analysis solid. Competitive moat through aviation certification is unique. Fraport pilot validates product-market fit.", decider: "Michael Braun", date: "2025-10-10T14:00:00Z" },
      { id: "g-005c", gate: "gate3", decision: "go", comment: "Business case compelling — 180% ROI, 14-month payback. Fraport scaling contract signed. Handing off to product management and marketing for launch Q1 2026.", decider: "Dr. Claudia Weiss", date: "2025-12-10T14:00:00Z" },
    ],
    createdAt: "2025-05-15T07:30:00Z",
  },
  {
    id: "opp-006",
    title: "Rail Track Inspection Drone Service",
    description: "Drone-based visual and thermal inspection service for railway infrastructure. Subscription model targeting European rail operators.",
    market: "Rail",
    owner: "Thomas Berger",
    stage: "closed",
    scoring: scoring(3, 2, 4, 2, 4, {
      marketAttractiveness: "Niche market (€800M) with strong incumbents like Fugro and Plasser & Theurer. Limited differentiation opportunity.",
      strategicFit: "Limited synergy with core portfolio. Would require building drone operations capability from scratch.",
      feasibility: "Drone technology mature. Integration with rail-specific inspection standards (EN 13848) achievable but requires domain expertise we lack.",
      commercialViability: "Subscription model viable but margins thin (35%). Price pressure from incumbents. Difficult to achieve scale without major operator partnership.",
      risk: "High competition from established inspection companies. BVLOS drone regulations still evolving. Railway-specific safety certifications complex.",
    }),
    gates: [
      { id: "g-006", gate: "gate1", decision: "no-go", comment: "Insufficient strategic fit — would require building entirely new capability. Market differentiation unclear against established players. Team recommends revisiting only if we acquire drone operations expertise.", decider: "Michael Braun", date: "2026-01-25T16:00:00Z" },
    ],
    createdAt: "2025-11-01T10:00:00Z",
  },
  {
    id: "opp-007",
    title: "Collaborative Welding Robot for Shipyards",
    description: "Lightweight cobot solution for automated welding in confined ship compartments. Reduces manual welding hours by 40% while maintaining classification standards.",
    market: "Robotics",
    owner: "Lisa Hoffmann",
    stage: "detailed_scoring",
    scoring: scoring(4, 5, 3, 4, 2, {
      marketAttractiveness: "Shipyards worldwide struggling with skilled welder shortage. 30% of welders retiring within 5 years. Automation rate in shipbuilding below 15%.",
      strategicFit: "Perfect fit with our robotics and maritime divisions. Combines two core competencies.",
      feasibility: "Requires custom end-effector development; 18-month timeline. Cobot platform (UR20) available off-the-shelf. Welding process qualification (AWS D1.1) needed.",
      commercialViability: "€150K per cobot system. Target 30 units Year 1. Recurring revenue from consumables and software updates (€20K/year).",
      risk: "Moderate technical risk in confined-space navigation. Market adoption may be slow in traditional shipyards. Classification society acceptance of cobot welds needs validation.",
    }),
    detailedScoring: {
      marketAttractiveness: {
        score: 4,
        analysis: {
          tam: "€6B global shipyard automation market (Frost & Sullivan 2025). Welding automation subset: €1.8B",
          sam: "€450M European and South Korean shipyards. Focus on mid-size yards building offshore vessels and cruise ships.",
          targetCustomers: "Meyer Werft (Germany), Fincantieri (Italy), HD Hyundai (Korea), Damen Shipyards (Netherlands). Mid-size yards with 2,000-8,000 employees.",
          customerRelationship: "Meyer Werft: existing customer for industrial robots. Fincantieri: discussions initiated through maritime trade shows. HD Hyundai: no relationship yet — need Korean partner.",
          competitors: "Pemamek (Finland, heavy welding automation), Kranendonk (Netherlands, pipe welding), Bug-O Systems (US, track welding). No cobot-specific competitor in confined spaces.",
          competitivePosition: "Unique: only cobot solution designed for confined compartments (<2m ceiling). Lighter (28kg) than any competitor. Welding quality matches manual welder output. Patent pending on confined-space path planning algorithm.",
        },
      },
      strategicFit: { score: 5, details: "Combines robotics division expertise (cobots, path planning) with maritime division domain knowledge (classification standards, shipyard workflows). Shared R&D with industrial welding team. CEO priority project — aligns with 'Smart Shipyard' strategic initiative launched Q1 2025." },
      feasibility: { score: 3, details: "Cobot platform: UR20 off-the-shelf (TRL 9). Custom end-effector: design phase complete, prototype in 4 months (TRL 5). Confined-space navigation: algorithm proven in simulation, real-world testing at Meyer Werft Q2 2026. AWS D1.1 welding qualification: 6-month certification process. Total timeline: 18 months to market-ready product." },
      commercialViability: { score: 4, details: "System price: €150K (cobot €45K + end-effector €35K + software €30K + integration €40K). Gross margin: 55%. Recurring: €20K/year software + consumables. Customer ROI: replaces 1.5 FTE welders (€75K/year each) — payback in 18 months. Year 1 target: 30 systems. Year 3: 120 systems (€18M + €2.4M recurring)." },
      risk: { score: 2, details: "Technical: confined-space navigation is novel but algorithm simulation results promising (98.5% collision avoidance). Market: welder shortage is structural — not cyclical. Regulatory: classification societies (Lloyd's, DNV) open to cobot welding — pilot program with DNV initiated. Supply chain: UR20 availability confirmed through 2028." },
    },
    gates: [
      { id: "g-007", gate: "gate1", decision: "go", comment: "Clear differentiation in a growing niche. Welder shortage is a structural problem that won't go away. Team has right competencies. Approved for detailed market and technical analysis.", decider: "Dr. Claudia Weiss", date: "2026-01-05T11:30:00Z" },
    ],
    createdAt: "2025-10-20T13:00:00Z",
  },
  {
    id: "opp-008",
    title: "Smart Grid Battery Management System",
    description: "Software platform for optimizing battery storage dispatch in industrial microgrids. AI-based forecasting for peak shaving and grid services revenue.",
    market: "Energy",
    owner: "Markus Schneider",
    stage: "gate1",
    scoring: scoring(4, 3, 4, 5, 2, {
      marketAttractiveness: "Industrial energy storage market CAGR 25% through 2030. EU energy crisis accelerating adoption. €12B market by 2028.",
      strategicFit: "Moderate fit — extends our industrial IoT platform but requires new energy trading domain expertise.",
      feasibility: "Core optimization algorithms exist from process industry projects. Battery integration APIs available. Energy market interface (EPEX SPOT) requires new development.",
      commercialViability: "SaaS model with recurring revenue; high margins (80%) after platform development. €5K/month per site. Revenue share on grid services (10% of customer earnings).",
      risk: "Low technical risk. Regulatory risk around grid services market rules (varies by country). Customer education needed — many industrial operators unfamiliar with battery storage economics.",
    }),
    gates: [],
    createdAt: "2025-12-15T08:00:00Z",
  },
];
