import { Opportunity, Scoring, GateRecord, Stage, BusinessPlanData, BusinessCase, createDefaultStrategicAnalyses, StrategicAnalyses, InvestmentCaseData } from "./types";

// Mock data uses old flat strategicAnalyses format; migrateStrategicAnalyses() in store handles conversion at runtime
const sa = (data: Record<string, any>): StrategicAnalyses => data as unknown as StrategicAnalyses;

function scoring(ma: number, sf: number, fe: number, cv: number, ri: number, comments: Record<string, string>): Scoring {
  return {
    marketAttractiveness: { id: "marketAttractiveness", score: ma, comment: comments.marketAttractiveness ?? "" },
    strategicFit: { id: "strategicFit", score: sf, comment: comments.strategicFit ?? "" },
    feasibility: { id: "feasibility", score: fe, comment: comments.feasibility ?? "" },
    commercialViability: { id: "commercialViability", score: cv, comment: comments.commercialViability ?? "" },
    risk: { id: "risk", score: ri, comment: comments.risk ?? "" },
  };
}

export const MOCK_OPPORTUNITIES: (Omit<Opportunity, 'strategicAnalyses' | 'businessPlan'> & { strategicAnalyses?: any; detailedScoring?: any; businessPlan?: any })[] = [
  {
    id: "a0000001-0008-4000-8000-000000000008",
    title: "Smart Grid Battery Management System",
    description: "Software platform for optimizing battery storage dispatch in industrial microgrids. AI-based forecasting for peak shaving and grid services revenue.",
    solutionDescription: "AI-powered battery storage optimization platform for industrial microgrids. Real-time dispatch for peak shaving, load shifting, and grid services (FCR, aFRR). EPEX SPOT integration for day-ahead and intraday energy trading. >95% forecast accuracy. Hardware-agnostic — supports all major BMS vendors. SaaS with revenue share on grid services earnings.",
    industry: "Energy",
    geography: "DACH / Benelux",
    technology: "AI / Energy Storage",
    owner: "Markus Schneider",
    ideaBringer: "Dr. Michael Vogt",
    stage: "gate1",
    scoring: scoring(4, 3, 4, 5, 2, {
      marketAttractiveness: "Industrial energy storage market CAGR 25% through 2030. EU energy crisis accelerating adoption. €12B market by 2028.",
      strategicFit: "Moderate fit — extends our industrial IoT platform but requires new energy trading domain expertise.",
      feasibility: "Core optimization algorithms exist from process industry projects. Energy market interface (EPEX SPOT) requires new development.",
      commercialViability: "SaaS model: €5K/month per site. Revenue share on grid services (10% of customer earnings). 80% margins at scale.",
      risk: "Low technical risk. Regulatory risk around grid services market rules varies by country.",
    }),
    roughScoringAnswers: {
      ma_market_size: 4, ma_growth_rate: 5, ma_customer_demand: 4, ma_competition: 3, ma_accessibility: 3,
      sf_strategy_alignment: 3, sf_competency_match: 3, sf_portfolio_synergy: 3, sf_customer_channel: 2,
      fe_technical_readiness: 4, fe_resources: 4, fe_timeline: 4, fe_dependencies: 3,
      cv_revenue_model: 5, cv_margins: 5, cv_scalability: 5, cv_payback: 4,
      ri_market_risk: 2, ri_technical_risk: 2, ri_execution_risk: 2, ri_financial_risk: 2,
    },
    roughScoringComments: {
      ma_market_size: "€18B global industrial energy storage software market by 2030 (BloombergNEF). DACH+Benelux: €2.8B.",
      ma_growth_rate: "25% CAGR — fastest growing market in portfolio. Energy crisis and falling battery costs converging.",
      ma_customer_demand: "BASF expressing strong interest for pilot. Multiple industrial customers asking about energy optimization.",
      ma_competition: "Fluence (Siemens/AES) market leader. Tesla Autobidder bundled with Megapack. Our IoT differentiation is niche.",
      ma_accessibility: "Some industrial IoT relationships transferable. Energy sector requires new contacts.",
      sf_strategy_alignment: "Moderate — extends IoT platform but requires new energy trading domain expertise.",
      sf_competency_match: "Data science and optimization transferable. Critical gap in energy markets knowledge.",
      sf_portfolio_synergy: "Good synergy with industrial IoT. Shared cloud infrastructure and data pipeline.",
      sf_customer_channel: "Industrial customers overlap partially. Energy trading buyers are different — new channel needed.",
      fe_technical_readiness: "Core optimization algorithms exist. EPEX SPOT integration requires 6 months new development.",
      fe_resources: "€2M seed budget approved. Cloud infrastructure ready. Need energy market data feeds.",
      fe_timeline: "12-month MVP realistic. Grid services certification adds 3-6 months.",
      fe_dependencies: "EPEX SPOT API access. Grid operator prequalification. Energy trading regulatory compliance.",
      cv_revenue_model: "SaaS + 10% revenue share on grid services — highly attractive aligned incentives.",
      cv_margins: "80% gross margin at scale — pure software. Best unit economics in portfolio.",
      cv_scalability: "Cloud-native, scales to thousands of sites. Marginal cost near zero per customer.",
      cv_payback: "Customer ROI <3 years at current energy prices. Breakeven at 15 sites (18 months target).",
      ri_market_risk: "Low — energy prices structurally high. Grid services demand growing. Battery costs falling.",
      ri_technical_risk: "Low — algorithms proven. EPEX SPOT integration standard. Real-time performance key challenge.",
      ri_execution_risk: "Moderate — need energy trading expertise hire quickly. Competitive talent market.",
      ri_financial_risk: "Low — modest €2M investment. Revenue share reduces customer acquisition risk.",
    },
    detailedScoring: {
      marketAttractiveness: {
        score: 4,
        analysis: {
          tam: "€18B global industrial energy storage software market by 2030 (BloombergNEF)",
          tamDescription: "All software platforms for battery storage optimization in industrial, commercial, and utility-scale applications. Includes dispatch optimization, forecasting, and grid services orchestration.",
          tamProjections: [{ year: 1, value: 4500 }, { year: 2, value: 5600 }, { year: 3, value: 7000 }, { year: 4, value: 8800 }, { year: 5, value: 11000 }],
          sam: "€2.8B DACH + Benelux industrial microgrid segment by 2030 — manufacturers with >1 MW battery installations",
          samDescription: "Industrial sites in DACH and Benelux with existing or planned battery storage >1 MW. Focus on manufacturing, logistics centers, and data centers with high energy costs and grid services potential.",
          samProjections: [{ year: 1, value: 500 }, { year: 2, value: 625 }, { year: 3, value: 780 }, { year: 4, value: 975 }, { year: 5, value: 1220 }],
          marketGrowthRate: "25% CAGR through 2030 — energy crisis, falling battery costs, and grid services revenue driving adoption",
          targetCustomers: "Large industrial energy consumers: BASF, ThyssenKrupp, BMW plants, DHL logistics hubs. Also data center operators (Equinix, NTT).",
          customerRelationship: "SaaS subscriptions with revenue-share on grid services earnings. Long-term contracts (3-5 years) with performance guarantees.",
          customerSegments: [
            { name: "Heavy manufacturing", size: 45, description: "Steel, chemicals, automotive — high energy costs, large battery installations" },
            { name: "Logistics & warehousing", size: 30, description: "Distribution centers with EV charging and solar — growing fast" },
            { name: "Data centers", size: 25, description: "UPS battery repurposing for grid services — high margin opportunity" },
          ],
          competitors: "Fluence (Siemens/AES), Tesla Autobidder, Stem Inc., enspired",
          competitivePosition: "Differentiated through industrial process integration — competitors focus on pure grid trading. Our IoT platform gives us unique load forecasting advantage.",
          competitorEntries: [
            { name: "Fluence", marketShare: 30, threatLevel: 4 },
            { name: "Tesla Autobidder", marketShare: 20, threatLevel: 3 },
            { name: "Stem Inc.", marketShare: 15, threatLevel: 3 },
          ],
          geographicalRegions: [
            { region: "Germany", potential: 5, marketSize: "€1.5B", notes: "Highest industrial energy costs in EU. Strong grid services market." },
            { region: "Netherlands", potential: 4, marketSize: "€600M", notes: "Fast-growing battery market. EPEX SPOT hub." },
            { region: "Belgium/Luxembourg", potential: 3, marketSize: "€350M", notes: "Smaller but well-regulated market with clear grid code." },
            { region: "Austria/Switzerland", potential: 3, marketSize: "€350M", notes: "Growing demand, favorable regulatory environment." },
          ],
        },
      },
      strategicFit: { score: 3, details: "Extends industrial IoT platform. Requires new energy trading domain expertise.",
        alignmentDimensions: [
          { key: "coreCompetency", label: "sfDimCore", current: 3, required: 5 },
          { key: "strategyAlign", label: "sfDimStrategy", current: 3, required: 4 },
          { key: "portfolioSynergy", label: "sfDimPortfolio", current: 4, required: 4 },
          { key: "customerBase", label: "sfDimCustomer", current: 2, required: 4 },
          { key: "technologyFit", label: "sfDimTech", current: 4, required: 5 },
          { key: "channelFit", label: "sfDimChannel", current: 2, required: 4 },
        ],
        capabilityGaps: [
          { id: "cg-008-1", capability: "Energy Trading Domain", currentLevel: 1, requiredLevel: 5, action: "Hire energy trading specialist. Partnership with EPEX SPOT for market access.", priority: "high" },
          { id: "cg-008-2", capability: "Battery Management Systems", currentLevel: 3, requiredLevel: 5, action: "Acquire or partner with BMS startup. Train existing IoT team.", priority: "high" },
          { id: "cg-008-3", capability: "Grid Regulatory Expertise", currentLevel: 2, requiredLevel: 4, action: "Engage regulatory consultancy for DACH grid codes. Join BDEW working groups.", priority: "medium" },
        ],
      },
      feasibility: { score: 4, details: "Core optimization algorithms exist. EPEX SPOT interface requires 6 months new development.", trl: 6, milestones: [
        { id: "ms-008-1", name: "Algorithm adaptation for energy", targetDate: "2026-04-01", status: "completed" },
        { id: "ms-008-2", name: "EPEX SPOT API integration", targetDate: "2026-07-15", status: "in_progress" },
        { id: "ms-008-3", name: "Pilot site deployment (BASF)", targetDate: "2026-10-01", status: "planned" },
        { id: "ms-008-4", name: "Grid services certification", targetDate: "2027-01-15", status: "planned" },
        { id: "ms-008-5", name: "Multi-site rollout", targetDate: "2027-04-01", status: "planned" },
      ] },
      commercialViability: {
        score: 5, details: "SaaS + revenue share model. 80% margins at scale.",
        pricingModel: "SaaS subscription + 10% revenue share on grid services",
        unitPrice: 60000, grossMargin: 80,
        projections: [
          { year: 1, revenue: 1200000, costs: 800000 },
          { year: 2, revenue: 3600000, costs: 1500000 },
          { year: 3, revenue: 8500000, costs: 2800000 },
          { year: 4, revenue: 16000000, costs: 4500000 },
          { year: 5, revenue: 28000000, costs: 7000000 },
        ],
        breakEvenUnits: 15,
      },
      risk: { score: 2, details: "Low technical risk. Regulatory uncertainty around grid services rules varies by country.", riskItems: [
        { id: "ri-008-1", name: "Grid services regulation change", category: "regulatory", probability: 3, impact: 4, mitigation: "Multi-country approach diversifies risk. Active participation in regulatory consultations." },
        { id: "ri-008-2", name: "Battery degradation liability", category: "technical", probability: 2, impact: 3, mitigation: "Conservative dispatch algorithms. Performance guarantees capped at battery warranty terms." },
        { id: "ri-008-3", name: "Competitor platform lock-in", category: "market", probability: 3, impact: 3, mitigation: "Open API architecture. Hardware-agnostic approach. Integration partnerships." },
      ] },
      organisationalReadiness: {
        score: 3,
        culture: "IoT team technically strong but no energy domain experience. Need cultural bridge between IT-driven IoT and regulated energy sector.",
        processes: "SaaS delivery processes mature. Need to add energy trading compliance, settlement reconciliation, and grid operator interfaces.",
        skills: "Strong data science and IoT platform skills. Critical gaps in energy markets, battery chemistry, and regulatory compliance.",
        leadership: "Innovation unit lead is sponsor. Needs stronger executive backing given moderate strategic fit.",
        resources: "€2M seed budget approved. Cloud infrastructure scalable. Need dedicated energy market data feeds (€200K/year).",
        stakeholders: "BASF (pilot site), EPEX SPOT (market access), TenneT (grid operator), BDEW (industry association).",
        details: "Competent team but significant domain knowledge gap. Success depends on hiring key energy trading expertise quickly.",
      },
    },
    strategicAnalyses: {
      ...createDefaultStrategicAnalyses(),
      ansoff: { position: "diversification", description: "New AI energy management product for the new industrial energy storage market.", rationale: "Energy storage optimization is a new market requiring new domain expertise (energy trading), even though our IoT platform provides a technology foundation." },
      threeHorizons: { horizon: "horizon2", description: "Smart grid battery management extends our IoT platform into the fast-growing energy sector.", rationale: "25% CAGR market with transferable technology. Revenue expected within 2-3 years but requires significant domain capability build-up." },
      bcg: { position: "question-mark", description: "Very high growth market (25% CAGR) but zero market share. Needs substantial investment in domain expertise.", rationale: "Market is growing faster than almost any other segment we track, but we have no energy trading credentials yet. Heavy investment required to compete." },
      mckinsey: { position: "invest-selectively", description: "Highly attractive industry (fast growth, high margins) but weak competitive position (no energy domain expertise).", rationale: "Industry is extremely attractive but our position is weak — strong IoT tech but critical domain knowledge gaps. Selective investment with clear milestones." },
      swot: {
        strengths: "Proven IoT platform with industrial-grade reliability. Strong data science and optimization algorithms. Existing industrial customer relationships. SaaS delivery expertise.",
        weaknesses: "No energy trading domain knowledge. No battery management system expertise. No EPEX SPOT or grid operator relationships. Small team with no energy sector experience.",
        opportunities: "Industrial energy costs at record highs. EU energy crisis accelerating battery storage adoption. Grid services revenue (FCR, aFRR) growing. Falling battery costs unlocking ROI.",
        threats: "Fluence (Siemens/AES) has massive scale. Tesla Autobidder bundled with Megapack. Energy-native startups (enspired, Stem) have domain expertise. Regulatory changes to grid services rules.",
        description: "Strong technology foundation but critical domain knowledge gap. Market timing is favorable but competitive landscape includes well-funded players.",
        rationale: "SWOT reveals this is a 'technology searching for domain expertise' play. Our IoT platform is genuinely differentiated for industrial loads — but we need energy trading know-how fast.",
      },
      pestel: {
        political: "EU energy crisis response accelerating storage deployment. German Energiewende policies support distributed storage. BDEW supportive of grid services from batteries.",
        economic: "Industrial electricity prices doubled since 2021. Grid services revenue (FCR) at €30K/MW/year. Battery costs falling 15% annually. Customer ROI typically <3 years.",
        social: "Energy security concerns driving self-sufficiency. Sustainability reporting (CSRD) makes clean energy investments visible. Workforce needs digital energy management skills.",
        technological: "LFP batteries mature and safe. EPEX SPOT API well-documented. AI forecasting accuracy >95% for day-ahead. Edge computing enables real-time dispatch.",
        environmental: "Battery storage enables higher renewable penetration. Peak shaving reduces grid carbon intensity. Circular economy for second-life EV batteries.",
        legal: "EnWG and StromNGV regulate grid services participation. Prequalification required for FCR/aFRR. GDPR applies to energy consumption data.",
        description: "Exceptionally favorable environment — economic drivers (high energy prices), political support (Energiewende), and technological readiness all converge.",
        rationale: "PESTEL is strongly positive across all dimensions. The economic driver alone (doubled electricity prices) makes the business case compelling for any industrial energy consumer.",
      },
      porter: {
        competitiveRivalry: { intensity: 4, description: "Fluence, Tesla, Stem, and enspired are all well-funded. Market growing fast enough for multiple winners but competition intense for early customers." },
        threatOfNewEntrants: { intensity: 3, description: "Energy trading expertise and grid operator prequalification create moderate barriers. Cloud platform development is capital-intensive." },
        threatOfSubstitutes: { intensity: 2, description: "Manual dispatch is the substitute — highly suboptimal and leaving money on the table. No real alternative to AI optimization." },
        bargainingPowerBuyers: { intensity: 3, description: "Large industrials (BASF, ThyssenKrupp) have negotiating power. But ROI is compelling and few alternatives with industrial process integration." },
        bargainingPowerSuppliers: { intensity: 2, description: "Cloud infrastructure (AWS/Azure) is commodity. EPEX SPOT API access is standardized. No critical supplier dependencies." },
        description: "Competitive market with well-funded players, but strong fundamentals: growing fast, no real substitute, and low supplier power.",
        rationale: "Porter confirms market is attractive despite competition. Our industrial IoT differentiation is meaningful — competitors focus on pure grid trading without process integration.",
      },
      valueChain: {
        stages: [
          { id: "vc-sg-1", name: "Battery Hardware / BMS", isOurPosition: false, marginAttractiveness: 2, differentiators: "Cell chemistry, BMS firmware, warranty terms", dynamics: "Commoditizing — CATL, BYD, Samsung dominate. We're hardware-agnostic." },
          { id: "vc-sg-2", name: "Optimization Software", isOurPosition: true, marginAttractiveness: 5, differentiators: "Forecast accuracy, dispatch algorithms, industrial process integration", dynamics: "Winner-take-most per site. Data network effects." },
          { id: "vc-sg-3", name: "Energy Market Interface", isOurPosition: true, marginAttractiveness: 4, differentiators: "EPEX SPOT integration, multi-market bidding, settlement automation", dynamics: "Regulatory expertise required. Changes frequently." },
          { id: "vc-sg-4", name: "Grid Services Aggregation", isOurPosition: true, marginAttractiveness: 5, differentiators: "Prequalification management, pool aggregation, performance guarantees", dynamics: "Recurring revenue. Trust-based relationship with TSOs." },
          { id: "vc-sg-5", name: "Customer Operations / Support", isOurPosition: true, marginAttractiveness: 3, differentiators: "24/7 monitoring, performance reporting, optimization recommendations", dynamics: "Essential for retention. Data-driven upselling." },
        ],
        description: "We capture value in software, energy market interface, and grid services aggregation — the highest-margin, stickiest parts of the value chain.",
        rationale: "Hardware-agnostic positioning is key: we avoid the commodity BMS layer and focus on intelligence and market access where margins are highest.",
      },
      customerSegmentation: {
        entries: [
          { id: "cs-008-1", name: "Heavy Manufacturing", size: "45%", needs: "Peak shaving, load shifting, grid services revenue, energy cost reduction", willingnessToPay: "High (€5K/month + revenue share — energy costs are 15-25% of opex)", priority: "high" },
          { id: "cs-008-2", name: "Logistics & Warehousing", size: "30%", needs: "EV charging optimization, solar self-consumption, demand charge management", willingnessToPay: "Medium-High (growing battery installations, ROI-driven decisions)", priority: "high" },
          { id: "cs-008-3", name: "Data Centers", size: "25%", needs: "UPS battery monetization for grid services, peak shaving, sustainability targets", willingnessToPay: "High (existing battery assets, pure revenue uplift from grid services)", priority: "medium" },
        ],
        description: "Three segments with different entry points. Manufacturing is primary target (largest pain). Data centers are highest margin (existing batteries).",
        rationale: "Segmentation aligns with battery installation patterns. Manufacturing has the most acute pain. Data centers offer 'free money' from existing UPS batteries.",
      },
      competitorAnalysis: {
        entries: [
          { id: "ca-008-1", name: "Fluence (Siemens/AES)", strengths: "Market leader, global scale, Siemens industrial relationships, proven platform (Fluence IQ)", weaknesses: "Focused on utility-scale, less attention to industrial microgrids, complex enterprise sales", marketShare: "30%", strategy: "Top-down from utility-scale to C&I segment", threatLevel: 4 },
          { id: "ca-008-2", name: "Tesla Autobidder", strengths: "Bundled with Megapack, strong brand, large install base", weaknesses: "Tesla-hardware-only, no third-party BMS support, limited grid services in EU", marketShare: "20%", strategy: "Vertical integration — sell hardware + software bundle", threatLevel: 3 },
          { id: "ca-008-3", name: "enspired", strengths: "European energy trading native, strong algorithmic trading, regulatory expertise", weaknesses: "Small team, limited industrial customer relationships, pure software", marketShare: "5%", strategy: "Pure-play energy trading optimization, partnering with hardware vendors", threatLevel: 3 },
        ],
        description: "Market split between large players (Fluence, Tesla) and nimble specialists (enspired). Our IoT industrial process integration is a unique angle.",
        rationale: "Competitors approach from energy trading or hardware perspective. Our entry via industrial IoT/process integration is genuinely differentiated.",
      },
      customerInterviewing: {
        entries: [
          { id: "ci-008-1", date: "2025-11-20", customerName: "BASF Ludwigshafen", role: "Head of Energy Management", keyInsights: "Energy costs are 20% of site opex. Currently manual dispatch — leaving €500K/year in grid services revenue on the table. Need integration with existing SCADA system.", painPoints: "Manual battery dispatch. No grid services participation. Energy cost unpredictability. Multiple BMS vendors on site.", quotes: "\"We have 15 MW of battery storage and we're barely using it intelligently. Show us €200K/year in grid services revenue and the business case writes itself.\"" },
          { id: "ci-008-2", date: "2025-12-10", customerName: "Equinix Frankfurt", role: "VP Data Center Operations", keyInsights: "70 MW of UPS batteries sitting idle 99.9% of the time. Could monetize for FCR. Need zero-risk approach — uptime is non-negotiable.", painPoints: "Stranded UPS battery capacity. Rising energy costs. Sustainability targets (carbon neutral by 2030). Board pressure for revenue diversification.", quotes: "\"If you can guarantee zero impact on uptime and generate €500K/year from our existing UPS batteries, we'll pilot within 3 months.\"" },
        ],
        description: "Interviews confirm two distinct value propositions: cost reduction for manufacturers, revenue generation for data centers.",
        rationale: "Both interviews validate compelling ROI cases. BASF represents the typical industrial customer; Equinix shows the data center 'stranded asset' opportunity.",
      },
    },
    gates: [],
    createdAt: "2025-12-15T08:00:00Z",
  },

  // ═══════════════════════════════════════════════════════════════════════════
];
