project_id = "rrqixaxjnfpjqqzlryxh"

[functions.ai-assessment]
verify_jwt = false

[functions.agent-chat]
verify_jwt = false

[functions.business-case-assessment]
verify_jwt = false

[functions.mark-web-research]
verify_jwt = false

[functions.sam-estimation]
verify_jwt = false
