// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-opportunities.ts
import { createClient } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";
function anonClient() {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var list_opportunities_default = defineTool({
  name: "list_opportunities",
  title: "List opportunities",
  description: "List innovation opportunities in the NOVI pipeline. Returns id, title, stage, industry, geography, owner, and creation date. Use `stage` to filter by pipeline stage and `limit` to cap results (default 25, max 200).",
  inputSchema: {
    stage: z.string().optional().describe("Optional pipeline stage filter, e.g. 'idea', 'assess', 'business_plan'."),
    limit: z.number().int().min(1).max(200).optional().describe("Maximum number of rows to return (default 25, max 200).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ stage, limit }) => {
    const supabase = anonClient();
    let q = supabase.from("opportunities").select("id, title, stage, industry, geography, owner, idea_bringer, created_at").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (stage) q = q.eq("stage", stage);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { opportunities: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-opportunity.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.25.76";
function anonClient2() {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var get_opportunity_default = defineTool2({
  name: "get_opportunity",
  title: "Get opportunity",
  description: "Fetch the full record for a single innovation opportunity by id, including scoring, business plan, business case, strategic analyses, go-to-market plan, and gates.",
  inputSchema: {
    id: z2.string().uuid().describe("The opportunity's UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }) => {
    const supabase = anonClient2();
    const { data, error } = await supabase.from("opportunities").select("*").eq("id", id).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return {
        content: [{ type: "text", text: `No opportunity found with id ${id}` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { opportunity: data }
    };
  }
});

// src/lib/mcp/tools/search-opportunities.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^3.25.76";
function anonClient3() {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var search_opportunities_default = defineTool3({
  name: "search_opportunities",
  title: "Search opportunities",
  description: "Full-text search opportunities by title, description, industry, technology, or solution. Returns id, title, stage, industry, and a short description snippet.",
  inputSchema: {
    query: z3.string().trim().min(1).describe("Search text to match across title, description, industry, technology, and solution."),
    limit: z3.number().int().min(1).max(100).optional().describe("Maximum number of rows to return (default 25, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    const supabase = anonClient3();
    const pattern = `%${query.replace(/[%,]/g, " ")}%`;
    const { data, error } = await supabase.from("opportunities").select("id, title, stage, industry, technology, description, solution_description, created_at").or(
      [
        `title.ilike.${pattern}`,
        `description.ilike.${pattern}`,
        `industry.ilike.${pattern}`,
        `technology.ilike.${pattern}`,
        `solution_description.ilike.${pattern}`
      ].join(",")
    ).order("created_at", { ascending: false }).limit(limit ?? 25);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { opportunities: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "novi-mcp",
  title: "NOVI Innovation Pipeline",
  version: "0.1.0",
  instructions: "Tools for exploring the NOVI innovation opportunity pipeline. Use `list_opportunities` to browse (optionally by stage), `search_opportunities` for keyword search across title/description/industry/technology, and `get_opportunity` to fetch the full record (scoring, business plan, business case, strategic analyses) by id.",
  tools: [list_opportunities_default, get_opportunity_default, search_opportunities_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
