UPDATE opportunities 
SET scoring = jsonb_set(
  scoring::jsonb, 
  '{detailed,risk}',
  '{
    "score": 3,
    "details": "Startup-typisches Risikoprofil: Runway-Risiko ist der kritischste Faktor. Key-Person-Dependency hoch. Enterprise-Sales ohne Track-Record ist die größte Unbekannte. AI-Abhängigkeit und Vendor-Lock-in als technologische Risiken. Marktvalidierung noch nicht abgeschlossen — Product-Market-Fit unbewiesen. Regulatorische Anforderungen (AI Act, GDPR) erfordern kontinuierliche Compliance-Investitionen.",
    "riskItems": [
      {"id":"ri-010-1","name":"Runway / Cash-Out-Risiko","category":"financial","probability":3,"impact":5,"mitigation":"Lean-Operations: Burn-Rate unter €25K/Monat. Seed-Runde (€400K) sichert 18 Monate Runway. Revenue-Meilensteine als Trigger für Follow-on-Finanzierung. Worst Case: Bridge-Loan oder Revenue-Based-Financing als Alternative zur Equity-Runde. Monatliches Cash-Monitoring mit 3 Szenarien (Best/Base/Worst)."},
      {"id":"ri-010-2","name":"Enterprise Sales Cycle vs. Runway","category":"execution","probability":4,"impact":4,"mitigation":"Fokus auf Mittelstand (kürzere Cycles, 2-4 Monate). Freemium/PLG-Motion für Self-Service-Adoption. Erst ab Year 2 echtes Enterprise-Selling. Risiko-Verstärker: Erste Kunden verlangen kostenlose Piloten (3-6 Monate), was den Revenue-Start weiter verzögert. Pipeline-Monitoring mit wöchentlichen Reviews."},
      {"id":"ri-010-3","name":"Key-Person-Dependency & Wissenskonzentration","category":"execution","probability":3,"impact":5,"mitigation":"Dokumentation aller Architektur-Entscheidungen in ADRs. Code-Reviews und Pair-Programming. Frühzeitig dritten Entwickler einstellen (ab Seed-Runde). Bus-Factor aktuell bei 1 für Backend/AI — kritisch. Knowledge-Base mit Runbooks für alle Deployment- und Ops-Prozesse aufbauen."},
      {"id":"ri-010-4","name":"Competitor Feature Catch-Up & VC-funded Konkurrenz","category":"market","probability":3,"impact":4,"mitigation":"Speed als Startup-Vorteil: Schnellere Feature-Releases als Legacy-Anbieter. AI-Differenzierung vertiefen (IDA als Unique Selling Point). Netzwerkeffekte durch Templates und Community aufbauen. Konkretes Risiko: Ein VC-finanzierter Wettbewerber mit €5M+ Budget könnte innerhalb von 12 Monaten ein vergleichbares Produkt launchen und mit aggressivem Pricing (Freemium) den Markt besetzen."},
      {"id":"ri-010-5","name":"GDPR, AI Act & Enterprise-Compliance-Anforderungen","category":"regulatory","probability":3,"impact":4,"mitigation":"EU-Hosting von Beginn an (Supabase EU). DPA-Template vorbereitet. Externer DSB ab 10 Kunden. AI Act Risiko: NOVI nutzt AI für Scoring und Assessments — Transparenzpflicht (Prompt Library als Vorteil). SOC 2 Type II erst ab Year 2 wirtschaftlich sinnvoll (€30-50K Kosten), aber Enterprise-Kunden fordern es ab Tag 1. Interim: Pentest-Report und Security-Fragebogen als Überbrückung."},
      {"id":"ri-010-6","name":"Gründer-Burnout & Teamstabilität","category":"execution","probability":3,"impact":4,"mitigation":"Klare Rollenverteilung im Gründerteam. Maximal 50h/Woche Commitment. Regelmäßige Retros. Advisor-Board als Sparring-Partner. Risiko verschärft sich durch Multi-Role-Belastung: Jeder Gründer ist gleichzeitig Entwickler, Vertriebler, Support und Geschäftsführer. Unterstützung durch Freelancer für nicht-kritische Aufgaben (Design, Content)."},
      {"id":"ri-010-7","name":"AI-Vendor-Lock-in & API-Kostenexplosion","category":"technical","probability":3,"impact":3,"mitigation":"Aktuell Abhängigkeit von wenigen AI-Providern (OpenAI, Google). API-Kosten pro Kunde bei geringer Nutzerbasis überproportional hoch (€50-100/Monat pro Kunde bei intensiver Nutzung). Mitigation: Multi-Provider-Architektur, lokale Modelle für einfache Tasks evaluieren (Ollama/Mistral), Token-Budget pro Assessment begrenzen. Langfristig: Eigene Fine-Tuned-Modelle für domänenspezifische Aufgaben."},
      {"id":"ri-010-8","name":"Product-Market-Fit Validierung verzögert sich","category":"market","probability":3,"impact":5,"mitigation":"Bisher nur 1 Demo und 1 Erstgespräch — kein validierter PMF. Risiko: Die Zielgruppe (Innovation-Teams im Mittelstand) existiert in der angenommenen Form nicht oder hat andere Prioritäten als angenommen. Mitigation: Schnelle Iteration mit 3-5 Pilotkunden innerhalb von 6 Monaten. Klare Kill-Kriterien definieren: Wenn nach 9 Monaten kein zahlender Kunde → Pivot oder Shutdown."},
      {"id":"ri-010-9","name":"Pricing-Druck durch Excel als Zero-Cost-Alternative","category":"market","probability":4,"impact":3,"mitigation":"73% der Zielgruppe nutzt Excel/PowerPoint — kostenlos und vertraut. Der wahrgenommene Mehrwert von NOVI muss den Preis von €18-36K/Jahr übersteigen. Risiko: Kunden sehen NOVI als nice-to-have, nicht als must-have. Mitigation: ROI-Rechner entwickeln (Zeiteinsparung pro Gate-Meeting quantifizieren), kostenlose Trial-Phase anbieten, AI-Features als Wow-Faktor nutzen."},
      {"id":"ri-010-10","name":"Skalierungsfalle: Vom Gründer-Vertrieb zum skalierbaren Sales","category":"execution","probability":3,"impact":4,"mitigation":"Die ersten 5-8 Kunden kommen über Gründer-Netzwerk (nicht skalierbar). Ab Kunde 10+ braucht es einen wiederholbaren Sales-Prozess. Risiko: Die Transition von Gründer-getriebenem zu prozess-getriebenem Vertrieb scheitert — typische Founders Trap. Mitigation: Ab Kunde 3 systematisch Sales-Playbook dokumentieren. Ersten AE erst einstellen, wenn der Prozess mindestens 3x funktioniert hat."}
    ]
  }'::jsonb
)
WHERE id = 'a0000001-0001-4000-8000-000000000010'